### ISSUE TITLE
Closed folds "consume" lineletters, possible to ignore?

### ISSUE THREAD

**Issue by Blake-LeBlanc** [skamsie/vim-lineletters#2]
Hello Alexandru!

When attempting to navigate a file with large closed folds, the lettering is "consumed" by the hidden folded rows. Would it be possible for it to refer to the fold itself as a single letter?

Here's a screenshot, notice how toward the bottom of the file, due to the folds, there are no more lineletters left to use.

![Screenshot_2020-12-18_12-31-33](https://user-images.githubusercontent.com/19244245/102648639-75c34f80-412d-11eb-9889-75d8ab89818f.png)

**Comment by skamsie** [comment]
Thanks for reporting! I never noticed this as I don't normally use folds. I will try to address this issue.
As a workaround you can extend the `prefix_chars` and then there will be more combinations available, for ex:

```
let g:lineletters_settings = { 'prefix_chars': [',', ';', 'j', 'f', 'k'] }
```

**Comment by skamsie** [comment]
Fixed by https://github.com/skamsie/vim-lineletters/commit/10428116fcfa8e6c136e3a198844b2f1132ed0de

@Blake-LeBlanc You can update the plugin and try the latest version. Please let me know if this is the behavior you expected.

**EDIT**

The functionality is fixed and works in both vim and neovim, however in vim only, the line that has the fold does not display the sign... it seems there is a limitation, see here: https://github.com/vim/vim/issues/5949

**Neovim**
<img width="504" alt="Screenshot 2020-12-18 at 21 58 07" src="https://user-images.githubusercontent.com/7014744/102661076-6cad9f00-417c-11eb-8738-f64a051dab38.png">

**Vim**
<img width="451" alt="Screenshot 2020-12-18 at 21 57 38" src="https://user-images.githubusercontent.com/7014744/102661129-89e26d80-417c-11eb-8812-8aa93e55cce8.png">

Anyway, you can still get to that specific line, but have to 'guess' the sign... in this case it's `m`

**Comment by Blake-LeBlanc** [comment]
That's perfect, works great! Thank you!
